version: 0.0
os: linux
files:
  - source: /
    destination: /opt/myproject

hooks:
  AfterInstall:
    - location: scripts/build.sh
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh
